### ISSUE TITLE
Event interface

### ISSUE THREAD

**Issue by waicool20** [waicool20/KAGA#12]
The 2017 Winter Event has started and KAGA has no proper event interface yet! Suggestions on UI changes would be welcome, so I can implement it quickly and start farming salt like no tomorrow!

**Comment by n0k0m3** [comment]
Rain of salt

Tanaka face

Taiha'd Kaga

Combat Ration + Akagi

**Comment by waicool20** [comment]
Created extra event mode button, it should change the options of the area dropdown box, will also hide the combined fleet option now when not checked, needs testing
