### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/sikuli/basics/HotkeyListener 	at org.sikuli.ide.Sikulix.main(Sikulix.java:31)

### ISSUE THREAD

**Issue by tamamo-chan** [waicool20/KAGA#13]
I have tried to setup your interface for a few hours and I can neither get your UI or the actual bot to work. I have tried everything I could think of. This is the error it returns in the debug:

```
[KAGA] [2017-02-16 04:47:56] [c.w.k.KancolleAuto] INFO - Starting new Kancolle Auto session
Exception in thread "main" java.lang.NoClassDefFoundError: org/sikuli/basics/HotkeyListener
	at org.sikuli.ide.Sikulix.main(Sikulix.java:31)
Caused by: java.lang.ClassNotFoundException: org.sikuli.basics.HotkeyListener
[KAGA] [2017-02-16 04:47:56] [c.w.k.KancolleAuto] INFO - Kancolle Auto session has terminated!
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[KAGA] [2017-02-16 04:47:56] [c.w.k.KancolleAuto] INFO - Kancolle Auto didn't terminate gracefully
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
feb. 16, 2017 4:47:56 AM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.waicool20.kaga.KancolleAuto.saveCrashLog(KancolleAuto.kt:71)
	at com.waicool20.kaga.KancolleAuto.handleCrash(KancolleAuto.kt:57)
	at com.waicool20.kaga.KancolleAuto.startAndWait(KancolleAuto.kt:44)
	at com.waicool20.kaga.views.KagaView$onStartStopButton$1.run(KagaView.kt:146)
	at java.lang.Thread.run(Unknown Source)
```

Edit: added code block

**Comment by waicool20** [comment]
Doesn't seem to be KAGA related exception, this is a problem with your sikulix script jar file. You might want to try reinstalling it. Make sure you're using sikulix v1.1+

Just in case could you post the config it generates?

**Comment by waicool20** [comment]
@lolipirate I take back what I said, there was some problem with KAGA not being able to read the version of kancolle auto properly and now it's fixed in a385d4e29c6e40e7572e36fe77063c16f0bc693d

Though I still don't think this is the root reason why your script won't work, try firing up the script one more time and post back the crash log here

**Comment by waicool20** [comment]
Closing due to lack of feedback

**Comment by tamamo-chan** [comment]
Hello, and sorry for not responding. I signed up with my spam email, which i rarely check, so I couldn't see you had answered. 

I reinstalled the files on the same drive, which seemed to fix the problem. However, my newest problem is that I'm unable to stop KAGA without ending the process in tasklist. I am also open KAGA after having used it before, without deleting the saved settings (KAGA folder).

**Comment by waicool20** [comment]
@lolipirate I cant really help you without more information, I'm not sure what would be a likely cause that might lead it to not be able to exit. Is this while running kancolle-auto?

Also if this is a separate problem from above, try opening a new issue to keep these things organized.

**Comment by waicool20** [comment]
@lolipirate I have fixed the problem where Kaga is not exiting properly
