### ISSUE TITLE
Loading Profile Issue Between Event and Non-event

### ISSUE THREAD

**Issue by tigurand** [waicool20/KAGA#14]
If I opened KAGA with event profile, then load the non-event profile, sortie area became 1-1, and vice versa. I just realized that I ran 1-1 for hours instead of 2-3.

**Comment by waicool20** [comment]
I've been able to recreate this, though it seems quite inconsistent, happening for some profiles and not for some.

**Comment by tigurand** [comment]
I have profile for E-3 and loaded it when I ran KAGA, then I switched to any normal non-event profile, it always became 1-1. After that it was normal when I load another non-event profile. But if I switch to event profile, it became 1-1 again.

**Comment by waicool20** [comment]
Try the latest commit, should be working properly now

**Comment by tigurand** [comment]
Thanks. It's working fine now.
