### ISSUE TITLE
Nightbattle set to True, get declined

### ISSUE THREAD

**Issue by n0k0m3** [waicool20/KAGA#19]
(x-post from mrmin123 kca repo as he said this should be reported here)
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): Latest commit ef2f095
* Viewer/browser: Chrome/KC3kai
* Operating system: Windows 7
**USED WITH KAGA**

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?: consistent

Although nightbattle is set to "true" for 2 last nodes, the script still decline NB. I ran the script w/o KAGA and changed lower case "true" to "True" and it worked again.

#### Console log (if applicable)
```
[2017-02-26 04:09:29] Continuing on to next node...
[log] CLICK on L(313,339)@S(0)[0,0 1600x900] (521 msec)
[log] CLICK on L(341,445)@S(0)[0,0 1600x900] (524 msec)
[2017-02-26 04:09:40] Spinning compass!
[log] CLICK on L(629,382)@S(0)[0,0 1600x900] (525 msec)
[2017-02-26 04:09:55] Selecting fleet formation!
[2017-02-26 04:11:48] Declining night battle!
[log] CLICK on L(327,314)@S(0)[0,0 1600x900] (528 msec)
[log] CLICK on L(407,490)@S(0)[0,0 1600x900] (528 msec)
[2017-02-26 04:12:09] Checking fleet condition...
[2017-02-26 04:12:12] Light damage: 0; moderate damage: 0; critical damage: 1
[log] CLICK on L(252,248)@S(0)[0,0 1600x900] (529 msec)
[2017-02-26 04:12:19] Checking fleet condition...
[2017-02-26 04:12:22] Light damage: 1; moderate damage: 0; critical damage: 1
[log] CLICK on L(506,448)@S(0)[0,0 1600x900] (536 msec)
[log] CLICK on L(762,505)@S(0)[0,0 1600x900] (527 msec)
[2017-02-26 04:13:06] Sortie complete!
```

#### Relevant config snippet (Copied from KAGA folder)
```
Formations = combinedfleet_4, combinedfleet_4, combinedfleet_3, combinedfleet_4
NightBattles = false, false, true, true
RetreatLimit = 2
RepairLimit = 1
```

**Comment by waicool20** [comment]
Hmm didn't know that lower cased booleans didn't work, I'll push a fix in a sec
