### ISSUE TITLE
Implement FatigueSwitch

### ISSUE THREAD

**Issue by mrmin123** [waicool20/KAGA#20]
As of [r8](https://github.com/mrmin123/kancolle-auto/releases/tag/8) kancolle-auto reads in the `FatigueSwitch` config option in the `SubmarineSwitch` section. Accepted values are `False` (default) and `True`. Wiki updates forthcoming.

Speaking of which, Python's boolean values are `True` and `False` (capital letter). While ConfigParser's `getboolean` can deal `true`/`false` and `0`/`1` values, it causes issues with a list of bools like with the night battle config: [kancolle-auto/#324](https://github.com/mrmin123/kancolle-auto/issues/324). If you could set it up so that KAGA outputs properly-cased bools for Python that'd be great.

**Comment by waicool20** [comment]
I've already dealt with the boolean issue in #19, just asking but does python not have a ignore case type of thing?

**Comment by mrmin123** [comment]
It does, and it certainly is possible to sanitize the input from within kancolle-auto, but I personally lean towards defensive programming more than overly fault-tolerant. i.e. if the user takes the time to provide the correct input, things will work as expected. Something like KAGA is obviously supposed to make that process a bit easier for the user, so as long as the outputs of KAGA conform to what's specified in the kancolle-auto wiki (case-sensitive) it should be fine.
