### ISSUE TITLE
SubmarineSwitch support

### ISSUE THREAD

**Issue by n0k0m3** [waicool20/KAGA#3]
Current version from latest commit still doesn't have submarine switch support. Also EnabledSubs value in the config get erased.

Suggestion:
- If you are planning to implement this, the new quest UI can also be used for choosing sub.
- If not, please add a call to change [SubmarineSwitch] Enabled to False to prevent further errors.

**Comment by waicool20** [comment]
SubmarineSwitch support added in e2c19a9054b95e45a741748873c8f6342bf3024d, closing issue
