### ISSUE TITLE
OpenJDK issue

### ISSUE THREAD

**Issue by Aripracc** [waicool20/KAGA#31]
I haven't been able to figure this out myself, but on linux OS using OpenJDK the Kaga jar will not launch due to not being able to find the  main class.

```
Error: Could not find or load main class com.waicool20.kaga.Kaga
```

It's pretty strange since the class is there. I've tried passing the class in via -classpath but the same issue occurs.

**Comment by Aripracc** [comment]
Found the issue here: https://github.com/kamilfb/mqtt-spy/issues/88

There could be a better error for this on OpenJDK's side.

**Comment by waicool20** [comment]
Same problem as #30, tho good on you for solving it by yourself
