### ISSUE TITLE
Event Mode missing Page 1 Area 1-3

### ISSUE THREAD

**Issue by frosty5689** [waicool20/KAGA#32]
Hi,

I am using the Spring 2017 event branch of kancolle-auto, but KAGA only shows Area 1-1 and 1-2 in drop down for page 1.

Not sure if this is a bug with KAGA or kancolle-auto, because it looks like you're automatically detecting event assets?

**Comment by waicool20** [comment]
mmm, yeah I'll patch that up. Event maps are hard coded in atm without detection: https://github.com/waicool20/KAGA/blob/master/src/main/kotlin/com/waicool20/kaga/views/tabs/sortie/SortieTabView.kt#L80

For a quick fix you can add 1-3 by yourself and recompile before I'm able to patch it

**Comment by frosty5689** [comment]
Created a pull request for it here: https://github.com/waicool20/KAGA/pull/33

**Comment by waicool20** [comment]
I'm writing a patch that will have better scanning, hard coding the events in isn't very future proof and won't work reliably in future events eg. Page 1 contains 2 maps only but 1-3 will show anyways. So I'll have to decline the pull request.

**Comment by frosty5689** [comment]
Yeah, should scan for current event assets' filename and dynamically generate the list.

**Comment by waicool20** [comment]
In a sense it currently is, but it just cuts off the aforementioned list in whatever last map it finds in kancolle-auto. I'll get to writing a better implementation when i get back home...but for now you can use that quick fix

**Comment by frosty5689** [comment]
One option is to just use a regex to match 1-1,1-2, 1-3, 2-1,2-2, etc from the _event_panel_ and then insert Page break placeholder above the first item that starts with 1, 2, 3 etc.

**Comment by waicool20** [comment]
Patched: e8b600a1140e8d1444c5454ed695a0aefb086f6c
