### ISSUE TITLE
reservedocks feature

### ISSUE THREAD

**Issue by Runarisu** [waicool20/KAGA#35]
1.7.0 release fixed fleetcomps and usebuckets options

however kaga still crashes due to "reservedocks" option being missing. I am unsure if latest commit has rectified this issue.

image attached
![reservedocks](https://cloud.githubusercontent.com/assets/20993370/26752970/3774bc80-489f-11e7-8e31-f409c1e5c137.jpg)

Sends KAGA into an endless loop.

**Comment by waicool20** [comment]
Ahh yeah ReserveDocks is missing, didn't realise that option was added

**Comment by waicool20** [comment]
Added this option in v1.7.1 :)

**Comment by waicool20** [comment]
ahh, forgot to push my changes derp
