### ISSUE TITLE
java.util.Timer.sched(unknown source) error

### ISSUE THREAD

**Issue by SomeGuyKyon** [waicool20/KAGA#36]
some error message comes up

> 
> java.lang.IllegalStateException: Task already scheduled or cancelled
> 	at java.util.Timer.sched(Unknown Source)
> 	at java.util.Timer.schedule(Unknown Source)
> 	at com.waicool20.kaga.util.LockPreventer.start(LockPreventer.kt:40)
> 	at com.waicool20.kaga.kcauto.KancolleAuto.startAndWait(KancolleAuto.kt:62)
> 	at com.waicool20.kaga.kcauto.KancolleAuto.startAndWait$default(KancolleAuto.kt:42)
> 	at com.waicool20.kaga.views.KagaView$startKancolleAuto$1.run(KagaView.kt:176)
> 	at java.lang.Thread.run(Unknown Source)

and debug window

> 
> [KAGA] [2017-06-11 18:16:33] [c.w.k.k.KancolleAuto] INFO - Starting new Kancolle Auto session
> [KAGA] [2017-06-11 18:16:33] [c.w.k.k.KancolleAuto] DEBUG - Launching with command: java -jar C:\kancolle-auto-master\sikulix.jar -r C:\kancolle-auto-master\kancolle_auto.sikuli
> [KAGA] [2017-06-11 18:16:33] [c.w.k.k.KancolleAuto] DEBUG - Session profile: {"general":{"offset":0,"recoveryMethod":"KC3","paranoia":0,"program":"Chrome","sleepModifier":0,"basicRecovery":true,"sleepCycle":20,"jstOffset":0},"scheduledSleep":{"length":3.6,"enabled":true,"startTime":"0030"},"scheduledStop":{"enabled":false,"count":5,"mode":"TIME"},"expeditions":{"enabled":true,"fleet2":"5","fleet3":"6","fleet4":"2"},"pvp":{"enabled":true,"fleetComp":1},"sortie":{"enabled":true,"area":"3","nodes":1,"repairTimeLimit":"0030","fleetComp":1,"subarea":"2","combinedFleet":false,"nodeSelects":[],"formations":["LINE_AHEAD"],"nightBattles":[false],"retreatLimit":2,"repairLimit":1,"checkFatigue":true,"portCheck":false,"medalStop":false,"lastNodePush":false},"submarineSwitch":{"enabled":true,"enabledSubs":["ALL"],"replaceLimit":1,"fatigueSwitch":true},"lbas":{"enabled":false,"enabledGroups":[],"group1Nodes":[],"group2Nodes":[],"group3Nodes":[]},"quests":{"enabled":false,"quests":["bd1","bd2","bd3","bd4","bd5","bd6","bd7","bd8","bw1","bw2","bw3","bw4","bw5","bw6","bw7","bw8","bw9","bw10","c2","c3","c4","c8","d2","d3","d4","d9","d11","e3","e4"],"checkSchedule":5},"name":"a"}
> 6﾿￹ 11, 2017 6:16:33 ﾿￀￈ￄ tornadofx.DefaultErrorHandler uncaughtException
> ﾽ￉ﾰﾢ: Uncaught error
> java.lang.IllegalStateException: Task already scheduled or cancelled
> 	at java.util.Timer.sched(Unknown Source)
> 	at java.util.Timer.schedule(Unknown Source)
> 	at com.waicool20.kaga.util.LockPreventer.start(LockPreventer.kt:40)
> 	at com.waicool20.kaga.kcauto.KancolleAuto.startAndWait(KancolleAuto.kt:62)
> 	at com.waicool20.kaga.kcauto.KancolleAuto.startAndWait$default(KancolleAuto.kt:42)
> 	at com.waicool20.kaga.views.KagaView$startKancolleAuto$1.run(KagaView.kt:176)
> 	at java.lang.Thread.run(Unknown Source)
> 
> [2017-06-11 18:16:42] Reading config file!
> [2017-06-11 18:16:42] Scheduled Sleep enabled: ~3.6 hours starting at ~0030
> [2017-06-11 18:16:42] Expeditions enabled: fleet 2: 5, fleet 3: 6, fleet 4: 2
> [2017-06-11 18:16:42] Combat enabled (PvP mode)
> [error] script [ C:\kancolle-auto-master\kancolle_auto.sikuli ] stopped with error in line 540
> [error] ConfigParser.NoOptionError ( No option 'fleetcomps' in section: 'Combat' )
> [error] --- Traceback --- error source first
> line: module ( function ) statement 
> 618: ConfigParser (  get ) ConfigParser.NoOptionError: No option 'fleetcomps' in section: 'Combat'
> 64: config_reader (  get_config )     for fleet in filter(None, config.get('Combat', 'FleetComps').replace(' ', '').split(',')):
> 355: main (  init )     settings, sleep_cycle = config_reader.get_config(settings, sleep_cycle)
> 434: main (  kancolle_auto_wrapper )     init()
> 540: main (  <module> )     kancolle_auto_wrapper()
> [error] --- Traceback --- end --------------

rebuilding the code didn't work.

**Comment by waicool20** [comment]
Update Kaga and Kancolle-auto, latest versions now use `fleetcomps` instead of `fleetcomp`

Also you may want to disable lock prevention since is somewhat buggy tho it usually works most of the time

**Comment by waicool20** [comment]
@SomeGuyKyon is the problem gone?

**Comment by SomeGuyKyon** [comment]
yup, it solved.
