### ISSUE TITLE
Not really an issue but

### ISSUE THREAD

**Issue by lainconnue** [waicool20/KAGA#38]
where do you locate the root directory of kancolle auto. I assume we are not talking about file paths here.

**Comment by waicool20** [comment]
If it's just a trivial question, you can ask on discord: https://discord.gg/2tt5Der

kancolle-auto root directory is where the file `config.ini` is located in

**Comment by lainconnue** [comment]
I would join but lacking the not expired discord invite, i think you would understand why I opened a ticket.

**Comment by waicool20** [comment]
The discord invite is still valid, optional if you join or not but best if you do so if you run into trivial problems then you can just ask freely since I will almost always respond within minutes if I'm not sleeping or out :p
