### ISSUE TITLE
Manual input in Repair Time Limit doesn't register

### ISSUE THREAD

**Issue by NanjoW** [waicool20/KAGA#39]
It looks like you are required to use the spinner you can't actually type in the box. When clicking save after manual entry it uses old value.

**Comment by waicool20** [comment]
You have to press enter for most typed input for it to be recognized.

**Comment by NanjoW** [comment]
That makes sense. After I found out about it, it was no problem, but I was bucketing low level subs for like an hour before I figured it out. Thought I would make a comment. You could probably add a listener for numeric inputs or something, but after you know it's really almost not worth the time. Thanks for clearing this  up thou. I was going crazy lol.

**Comment by waicool20** [comment]
Lul maybe I will add listeners for that soon :tm: ill close this issue now
