### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by n0k0m3** [waicool20/KAGA#4]
- Time zone chooser: For each time zone set JSTOffset accordingly
- Expedition/PVP can be combined into 1 tab for compact UI, same as General and Scheduling, 2 columns/tab may be a good choice
- Submarine switch support #3 
- Damage Limit to dropdown choices: Minor, Moderate, Heavily Damaged
- Include checkbox after Repair Time Limit for enforce bucket use when OCR failed (RepairTimeLimit: 9500)
- Backup config by rename original config to config.ini.bak and restore from backup

**Comment by waicool20** [comment]
JSTOffset is already calculated automatically using the host systems timezone.

Ill get to the others when I'm finish with the formations chooser

**Comment by waicool20** [comment]
Damage limits were changed to dropdown choices in c1edaa2458309721f6e51e133e2bd0135a458c15

**Comment by waicool20** [comment]
Kaga now backups the config.ini in the kancolle-auto directory on the first load or if it cannot load the current profile specified in the kaga config file as of e489c642893a8e9b573551f751da5927775f154d

**Comment by waicool20** [comment]
Implemented most features here except combining the tabs and the checkbox for the repair time limit, which I think is unnecessary, also to keep things clean. So I'm closing this issue
