### ISSUE TITLE
Crashing due to new section in kcauto

### ISSUE THREAD

**Issue by czevolk** [waicool20/KAGA#41]
The latest version of kcauto has added an [EventReset] which is causing it to fail to start since it doesn't exist in KAGA.

[error] script [ C:\Games\kcauto-kai\kcauto.sikuli ] stopped with error in line 38
[error] ConfigParser.NoSectionError ( No section: 'EventReset' )
[error] --- Traceback --- error source first
line: module ( function ) statement 
368: ConfigParser (  getboolean )   File "C:\Program Files\Sikuli\sikulix.jar\Lib\ConfigParser.py", line 607, in get
77: config (  read )     if config.getboolean('EventReset', 'Enabled'):
44: config (  __init__ )     self.read()
[error] --- Traceback --- end --------------

**Comment by waicool20** [comment]
Already implemented in commit 0fa7ca1247c00a376f2a1a939733c6fa41990c35

Wait for an official release over here on github or download a "nightly" at https://ci.appveyor.com/project/waicool20/kaga
