### ISSUE TITLE
Quest ID not saved as lowercase

### ISSUE THREAD

**Issue by silfumus** [waicool20/KAGA#6]
**Environment**
kancolle-auto version: Release 6.1 (2017-1-1)
KAGA version: v1.1.1

Quests section in KAGA-supplied config.ini doesn't work since kancolle-auto only recognized quest ID in lowercase (e.g: bd1, e3). Converting the quest ID to lowercase and run kancolle-auto manually fixed the problem.

Not sure why this hasn't been reported yet.

**Comment by waicool20** [comment]
Fixed in d12eda7198f703bdb77f30aa06d6f1fecb7179d3 released in v1.1.2

**Comment by waicool20** [comment]
Reopened because quests stays as uppercase if KAGA loads a config and the user does not configure it in the quest chooser.
