### ISSUE TITLE
Compatibility with Sikuli 1.1.1

### ISSUE THREAD

**Issue by mrmin123** [waicool20/KAGA#8]
Hi @waicool20 , just a heads up that I'm going to be updating kancolle-auto to run off of the newer SikuliX 1.1.1 nightlies (see [kancolle-auto#261](https://github.com/mrmin123/kancolle-auto/issues/261))

A working version of kancolle-auto with the changes exists in [this branch](https://github.com/mrmin123/kancolle-auto/tree/261_sikuli_upgrade) (261_sikuli_upgrade). Primary change is that instead of `sikuli-script.jar` it runs off of `sikulix.jar` now. The README on the WIP branch has install instructions for the new version of Sikuli. I'm still testing the branch but it should be merged in by the end of the day from my end.

Thanks!

**Comment by waicool20** [comment]
@mrmin123 I've created a new branch over here with the required changes to allow the new sikulix.jar: 9caa4428ffda394511a6c31b3adf761de0c2c8a7

However it's not really working for me, not sure if it's a problem with Kancolle Auto or KAGA, but anyways I get this error, I'll merge the branch when this gets fixed.

>[info] runcmd: lsb_release -i -r -s 
[2017-01-23 10:44:03] Reading config file!
[2017-01-23 10:44:03] Expeditions enabled: fleet 2: 2
[2017-01-23 10:44:03] Reading util config file!
[2017-01-23 10:44:03] Config successfully loaded!
[2017-01-23 10:44:03] Starting kancolle_auto!
[2017-01-23 10:44:03] Finding window!
[2017-01-23 10:44:03] Focus on KanColle!
[error] switchApp: could not identify process with search name 'KC3'
[error] App.focus failed:  [-1:KC3 ()] KC3
[error] script [ /home/waicool20/bin/kancolle-auto/kancolle_auto.sikuli ] stopped with error in line 523
[error] AttributeError ( 'NoneType' object has no attribute 'focusedWindow' )
[error] --- Traceback --- error source first
line: module ( function ) statement 
48: main (  focus_window )     kc_window = myApp.focusedWindow()
335: main (  init )     focus_window()
417: main (  kancolle_auto_wrapper )     init()
523: main (  <module> )     kancolle_auto_wrapper()
[error] --- Traceback --- end --------------

Config generated by KAGA: 

>[General]
>Program = KC3
>RecoveryMethod = KC3
>BasicRecovery = true
>JSTOffset = -1
>SleepCycle = 3
>Paranoia = 1
>SleepModifier = 0
>
>[ScheduledSleep]
>Enabled = false
>StartTime = 1000
>SleepLength = 3.5
>
>[ScheduledStop]
>Enabled = false
>Mode = TIME
>Count = 10
>
>[Expeditions]
>Enabled = true
>Fleet2 = 2
>Fleet3 = 
>Fleet4 = 
>
>[PvP]
>Enabled = false
>FleetComp = 1
>
>[Combat]
>Enabled = false
>FleetComp = 1
>Area = 3
>Subarea = 2
>CombinedFleet = false
>Nodes = 1
>NodeSelects = 
>Formations = line_ahead
>NightBattles = false
>RetreatLimit = 2
>RepairLimit = 1
>RepairTimeLimit = 100
>CheckFatigue = true
>PortCheck = false
>MedalStop = false
>LastNodePush = false
>
>[SubmarineSwitch]
>Enabled = false
>EnabledSubs = all
>
>[LBAS]
>Enabled = false
>EnabledGroups = 
>Group1Nodes = 
>Group2Nodes = 
>Group3Nodes = 
>
>[Quests]
>Enabled = false
>Quests = Bd1, Bd2, Bd3, Bd4, Bd5, Bd6, Bd7, Bd8, Bw1, Bw2, Bw3, Bw4, Bw5, Bw6, Bw7, Bw8, Bw9, Bw10, C2, C3, C4, C8, D2, D3, D4, D9, D11, E3, E4
>CheckSchedule = 5

**Comment by waicool20** [comment]
Ok so weirdly enough it works when I put Chrome (or Chromium since I'm on linux) as the program, it manages to find the window. But it doesn't really work if there are 2 or more windows.

**Comment by mrmin123** [comment]
Unfortunately a failure to find the window is beyond my and kancolle-auto's controls. Is the KC3 window on a second monitor? I know Sikuli has issues with that.

BTW I noticed in your config that Quests are still showing up with upper case characters... I thought this was resolved in #6? Or maybe it's just not refreshed in that particular config file.

**Comment by waicool20** [comment]
Oh yeah, didn't notice that, I think it's because KAGA read the config with upper case as is.The code where it saves it to lowercase is only run when you save in the quest chooser. And since I almost never use the quest module it never converted. I guess I'll fix that later.

And no not running dual monitor, I guess I'll close this since I found a workaround. Just havd to keep note since this didn't happen before the sikuli upgrade. With that said I'm totally loving the increase of speed.
